image:
    file: .gitpod.dockerfile

tasks:
  - init: npm install
    command: |
      mkdir -p /workspace/data && mongod --dbpath /workspace/data
      npm run docs
      npm run watch
    
ports:
  - port: 3000
    onOpen: open-preview
