image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      npm install
      npm run build
      mkdir -p /workspace/data && mongod --dbpath /workspace/data
    command: npm run server

ports:
  - port: 3000
    onOpen: open-preview
