image:
  file: .gitpod.dockerfile

tasks:
    - init: npm install
      command: |
        npm run docs
        npm run watch

    - command: mkdir -p /workspace/data && mongod --dbpath /workspace/data --bind_ip 0.0.0.0
    
ports:
  - port: 3000
    onOpen: open-preview

  - port: 27017
    visibility: public

